const VITA_DATA = {
  brand: "VitaPure 純萃",
  tagline: "科學配方 · 天然純淨 · 守護每一天",

  categories: [
    { id: "all", name: "全部產品" },
    { id: "vitamins", name: "維生素礦物質" },
    { id: "protein", name: "蛋白質與胺基酸" },
    { id: "omega", name: "魚油與脂肪酸" },
    { id: "probiotics", name: "益生菌" },
    { id: "herbal", name: "草本萃取" },
    { id: "beauty", name: "美容保養" },
  ],

  products: [
    {
      id: 1,
      name: "綜合維他命 B 群 Plus",
      category: "vitamins",
      emoji: "💊",
      price: 680,
      originalPrice: 850,
      rating: 4.8,
      reviews: 324,
      tag: "熱銷",
      desc: "八種 B 群維生素完整配方，支援能量代謝與神經系統健康。",
      ingredients: "維生素 B1、B2、B6、B12、葉酸、生物素、泛酸、菸鹼酸",
      usage: "每日 1 顆，餐後服用",
      benefits: ["提升日常活力", "支援神經系統", "促進能量代謝"],
    },
    {
      id: 2,
      name: "高純度深海魚油 Omega-3",
      category: "omega",
      emoji: "🐟",
      price: 980,
      originalPrice: 1200,
      rating: 4.9,
      reviews: 512,
      tag: "編輯推薦",
      desc: "EPA + DHA 高濃度配方，採用分子蒸餾技術去除重金屬。",
      ingredients: "EPA 360mg、DHA 240mg、維生素 E",
      usage: "每日 2 顆，餐後服用",
      benefits: ["心血管健康", "大腦認知功能", "抗發炎支援"],
    },
    {
      id: 3,
      name: "乳清蛋白 Isolate 巧克力",
      category: "protein",
      emoji: "🥤",
      price: 1280,
      originalPrice: 1480,
      rating: 4.7,
      reviews: 289,
      tag: null,
      desc: "90% 蛋白質含量，低乳糖，運動後快速補充優質蛋白。",
      ingredients: "乳清蛋白分離物、可可、天然香料",
      usage: "每次 1 匙（30g）加入 250ml 水或牛奶",
      benefits: ["肌肉修復", "增加飽足感", "運動後恢復"],
    },
    {
      id: 4,
      name: "100 億活菌益生菌複方",
      category: "probiotics",
      emoji: "🦠",
      price: 890,
      originalPrice: 1090,
      rating: 4.6,
      reviews: 198,
      tag: "新品",
      desc: "10 種菌株、100 億 CFU，耐胃酸包覆技術確保活菌到達腸道。",
      ingredients: "乳酸菌、雙歧桿菌、菊糖（益生元）",
      usage: "每日 1 顆，空腹或睡前服用",
      benefits: ["腸道菌群平衡", "改善消化", "增強免疫力"],
    },
    {
      id: 5,
      name: "膠原蛋白胜肽 + 維生素 C",
      category: "beauty",
      emoji: "✨",
      price: 1180,
      originalPrice: 1380,
      rating: 4.8,
      reviews: 445,
      tag: "熱銷",
      desc: "小分子膠原蛋白胜肽，搭配維生素 C 促進膠原蛋白合成。",
      ingredients: "魚膠原蛋白胜肽 5000mg、維生素 C 100mg",
      usage: "每日 1-2 包，加入飲品中",
      benefits: ["皮膚彈性", "關節保健", "抗氧化"],
    },
    {
      id: 6,
      name: "南非醉茄舒壓複方",
      category: "herbal",
      emoji: "🌿",
      price: 750,
      originalPrice: null,
      rating: 4.5,
      reviews: 156,
      tag: null,
      desc: "阿育吠陀傳統草本，協助身體適應壓力、改善睡眠品質。",
      ingredients: "南非醉茄萃取、L-茶胺酸、鎂",
      usage: "每日 1 顆，睡前 1 小時服用",
      benefits: ["減輕壓力", "改善睡眠", "平衡皮質醇"],
    },
    {
      id: 7,
      name: "維生素 D3 + K2 複方",
      category: "vitamins",
      emoji: "☀️",
      price: 520,
      originalPrice: 650,
      rating: 4.7,
      reviews: 267,
      tag: null,
      desc: "D3 促進鈣吸收，K2 引導鈣質進入骨骼而非血管。",
      ingredients: "維生素 D3 2000IU、維生素 K2 MK-7 100mcg",
      usage: "每日 1 顆，隨餐服用",
      benefits: ["骨骼健康", "免疫力", "心血管保護"],
    },
    {
      id: 8,
      name: "綜合蔬果酵素粉",
      category: "herbal",
      emoji: "🥬",
      price: 890,
      originalPrice: 990,
      rating: 4.4,
      reviews: 134,
      tag: null,
      desc: "32 種蔬果酵素，幫助消化、補充日常膳食纖維不足。",
      ingredients: "綜合蔬果酵素、膳食纖維、益生菌",
      usage: "每日 1 包，餐後服用",
      benefits: ["促進消化", "排毒代謝", "補充植化素"],
    },
  ],

  nutrients: [
    { name: "維生素 D", role: "骨骼健康、免疫調節", source: "曬太陽、魚油、蛋黃", daily: "1000-2000 IU" },
    { name: "Omega-3 (EPA/DHA)", role: "心血管、大腦功能", source: "深海魚、藻油", daily: "1000-2000 mg" },
    { name: "維生素 B12", role: "神經系統、紅血球生成", source: "肉類、乳製品、B12 補充品", daily: "2.4 mcg" },
    { name: "鎂", role: "肌肉放鬆、睡眠、能量代謝", source: "堅果、深綠蔬菜、全穀", daily: "310-420 mg" },
    { name: "鋅", role: "免疫力、傷口癒合", source: "牡蠣、瘦肉、南瓜子", daily: "8-11 mg" },
    { name: "益生菌", role: "腸道健康、免疫調節", source: "發酵食品、益生菌補充品", daily: "10-100 億 CFU" },
    { name: "膠原蛋白", role: "皮膚彈性、關節軟骨", source: "骨湯、魚皮、膠原蛋白粉", daily: "2.5-10 g" },
    { name: "輔酶 Q10", role: "細胞能量、抗氧化", source: "內臟肉類、補充品", daily: "100-200 mg" },
  ],

  blogPosts: [
    {
      id: 1,
      title: "如何挑選適合自己的綜合維他命？",
      date: "2026-05-15",
      category: "保健知識",
      excerpt: "綜合維他命種類繁多，本文從年齡、性別、生活型態三個面向幫您找到最適合的配方。",
      content: "選擇綜合維他命時，首先要評估自己的飲食缺口。外食族可能缺乏 B 群與維生素 C；久坐辦公族則需要更多維生素 D。建議選擇有第三方檢驗認證的品牌，並注意劑量是否過量...",
    },
    {
      id: 2,
      title: "魚油 vs 藻油：Omega-3 補充完全指南",
      date: "2026-05-08",
      category: "營養科學",
      excerpt: "素食者該選藻油嗎？魚油和藻油的 EPA、DHA 比例有何不同？一次搞懂。",
      content: "魚油是最常見的 Omega-3 來源，富含 EPA 和 DHA。藻油則適合素食者，但 DHA 含量較高而 EPA 較低。若為心血管保健，建議選擇 EPA 含量較高的魚油配方...",
    },
    {
      id: 3,
      title: "運動後該補充蛋白質嗎？時機與份量解析",
      date: "2026-04-28",
      category: "運動營養",
      excerpt: "運動後 30 分鐘黃金窗口是真的嗎？乳清、酪蛋白、大豆蛋白如何選擇？",
      content: "運動後補充蛋白質有助於肌肉修復，但「30 分鐘窗口」並非絕對。重點在於每日總蛋白質攝取量是否足夠。一般建議每公斤體重攝取 1.2-2.0 克蛋白質...",
    },
    {
      id: 4,
      title: "腸道健康與免疫力：益生菌怎麼吃才有效？",
      date: "2026-04-12",
      category: "腸道保健",
      excerpt: "益生菌種類、劑量、服用時間都會影響效果，讓專業營養師告訴您關鍵細節。",
      content: "益生菌的效果取決於菌株種類、活菌數量（CFU）及是否具備耐胃酸包覆技術。建議選擇有臨床研究支持的菌株，如 Lactobacillus acidophilus 和 Bifidobacterium longum...",
    },
  ],

  faqs: [
    { q: "補健品可以取代正常飲食嗎？", a: "不行。補健品是「補充」而非「取代」。均衡飲食仍是獲取營養素的最佳方式，補健品用於填補特定營養缺口。" },
    { q: "懷孕或哺乳期可以服用嗎？", a: "部分成分（如高劑量維生素 A、某些草本）不適合孕婦。請在服用前諮詢您的婦產科醫師，我們也提供專屬孕婦配方系列。" },
    { q: "多久才會看到效果？", a: "因成分而異。B 群約 1-2 週可能有感；魚油約 4-8 週；膠原蛋白約 8-12 週。建議持續服用至少一個月並觀察身體變化。" },
    { q: "可以同時服用多種補健品嗎？", a: "大多數產品可以搭配，但需注意重複成分（如多種含鐵配方）可能導致過量。建議使用我們的健康測驗或諮詢營養師。" },
    { q: "產品有通過檢驗嗎？", a: "全系列產品均通過 SGS 食品檢驗，並符合 GMP 良好製造規範。每批次提供檢驗報告編號供查詢。" },
    { q: "如何保存補健品？", a: "請存放於陰涼乾燥處，避免陽光直射。開封後建議 6 個月內食用完畢。益生菌建議冷藏保存以維持活菌活性。" },
  ],

  quizQuestions: [
    {
      question: "您的年齡區間？",
      options: [
        { text: "18-30 歲", scores: { energy: 2, beauty: 1 } },
        { text: "31-45 歲", scores: { heart: 1, energy: 1, beauty: 2 } },
        { text: "46-60 歲", scores: { heart: 2, bone: 2, energy: 1 } },
        { text: "60 歲以上", scores: { bone: 3, heart: 2, gut: 1 } },
      ],
    },
    {
      question: "您最關注的健康目標？",
      options: [
        { text: "提升活力、減少疲勞", scores: { energy: 3 } },
        { text: "心血管與大腦保健", scores: { heart: 3 } },
        { text: "皮膚保養與抗老化", scores: { beauty: 3 } },
        { text: "腸道消化與免疫力", scores: { gut: 3 } },
      ],
    },
    {
      question: "您的飲食型態？",
      options: [
        { text: "均衡飲食，偶爾外食", scores: { energy: 1 } },
        { text: "經常外食、飲食不规律", scores: { energy: 2, gut: 2 } },
        { text: "素食或蛋奶素", scores: { heart: 2, energy: 1 } },
        { text: "健身/高蛋白飲食", scores: { energy: 2, beauty: 1 } },
      ],
    },
    {
      question: "您是否有運動習慣？",
      options: [
        { text: "每週 3 次以上", scores: { energy: 2, beauty: 1 } },
        { text: "每週 1-2 次", scores: { energy: 1 } },
        { text: "很少運動", scores: { heart: 1, bone: 1 } },
        { text: "幾乎不運動", scores: { heart: 2, bone: 2, gut: 1 } },
      ],
    },
    {
      question: "您的睡眠品質？",
      options: [
        { text: "很好，一覺到天亮", scores: {} },
        { text: "普通，偶爾失眠", scores: { energy: 1 } },
        { text: "經常睡不好", scores: { energy: 2, heart: 1 } },
        { text: "長期失眠或壓力大", scores: { energy: 3, heart: 1 } },
      ],
    },
  ],

  quizResults: {
    energy: { title: "活力能量組合", products: [1, 3, 6], desc: "建議補充 B 群維生素提升代謝，乳清蛋白支持肌肉恢復，南非醉茄幫助舒壓。" },
    heart: { title: "心腦健康組合", products: [2, 7], desc: "深海魚油支援心血管，維生素 D3+K2 強化骨骼與免疫。" },
    beauty: { title: "美麗養顏組合", products: [5, 2], desc: "膠原蛋白胜肽呵護肌膚，Omega-3 由內而外抗氧化。" },
    gut: { title: "腸道免疫組合", products: [4, 8], desc: "益生菌平衡腸道菌群，蔬果酵素促進消化吸收。" },
    bone: { title: "骨骼強健組合", products: [7, 2, 5], desc: "D3+K2 促進鈣吸收，魚油抗發炎，膠原蛋白保護關節。" },
  },
};
